// src/components/calendar/CalendarView.tsx
import React, { useState, useEffect } from 'react';
import { Calendar as CalendarIcon, Clock, MapPin, Plus, Trash2, Users, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { CalendarEvent } from '../../types';
import { api } from '../../services/api';

export const CalendarView: React.FC = () => {
  const { currentUser, addToast } = useApp();
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newDescription, setNewDescription] = useState('');
  const [newStart, setNewStart] = useState('');
  const [newEnd, setNewEnd] = useState('');
  const [newLocation, setNewLocation] = useState('');

  const loadEvents = async () => {
    const res = await api.getCalendarEvents();
    if (res.success && res.data) {
      setEvents(res.data);
    }
  };

  useEffect(() => {
    loadEvents();
  }, []);

  const handleCreateEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle || !newStart) return;

    const res = await api.createCalendarEvent({
      title: newTitle.trim(),
      description: newDescription.trim(),
      startAt: new Date(newStart).toISOString(),
      endAt: newEnd ? new Date(newEnd).toISOString() : new Date(Date.now() + 3600000).toISOString(),
      location: newLocation.trim()
    });

    if (res.success && res.data) {
      setEvents(prev => [...prev, res.data]);
      setIsCreateModalOpen(false);
      setNewTitle('');
      setNewDescription('');
      setNewStart('');
      setNewEnd('');
      setNewLocation('');
      addToast('Evento programado con éxito', 'success');
    }
  };

  const handleDeleteEvent = async (id: string) => {
    await api.deleteCalendarEvent(id);
    setEvents(prev => prev.filter(e => e.id !== id));
    addToast('Evento eliminado del calendario', 'info');
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-900/60 overflow-hidden text-xs">
      {/* Header */}
      <div className="h-14 bg-slate-950/70 border-b border-slate-800 px-6 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2">
          <CalendarIcon className="w-5 h-5 text-amber-400" />
          <h2 className="font-bold text-slate-100 text-sm">Calendario de Equipo & Eventos</h2>
        </div>

        <button
          onClick={() => setIsCreateModalOpen(true)}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-600 hover:bg-amber-500 text-white font-semibold transition-colors shadow-md shadow-amber-600/20"
        >
          <Plus className="w-4 h-4" />
          <span>Nuevo Evento</span>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {events.length === 0 ? (
            <div className="col-span-full py-16 text-center text-slate-500">
              No hay eventos programados en este momento.
            </div>
          ) : (
            events.map(evt => (
              <div
                key={evt.id}
                className="p-4 rounded-xl bg-slate-950/70 border border-slate-800 hover:border-amber-500/40 transition-all shadow-sm space-y-3 group"
              >
                <div className="flex items-start justify-between">
                  <div className="min-w-0">
                    <span className="text-[10px] font-semibold text-amber-400 uppercase tracking-wider">
                      {new Date(evt.startAt).toLocaleDateString([], { weekday: 'long', month: 'short', day: 'numeric' })}
                    </span>
                    <h3 className="font-bold text-slate-100 text-sm mt-0.5">{evt.title}</h3>
                  </div>
                  <button
                    onClick={() => handleDeleteEvent(evt.id)}
                    className="opacity-0 group-hover:opacity-100 p-1 text-slate-500 hover:text-rose-400 transition-opacity"
                    title="Eliminar evento"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>

                {evt.description && (
                  <p className="text-slate-400 text-xs leading-relaxed">{evt.description}</p>
                )}

                <div className="space-y-1.5 pt-2 border-t border-slate-800/80 text-[11px] text-slate-400">
                  <div className="flex items-center gap-2">
                    <Clock className="w-3.5 h-3.5 text-slate-500" />
                    <span>
                      {new Date(evt.startAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} -{' '}
                      {new Date(evt.endAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                  {evt.location && (
                    <div className="flex items-center gap-2">
                      <MapPin className="w-3.5 h-3.5 text-slate-500" />
                      <span className="truncate">{evt.location}</span>
                    </div>
                  )}
                  {evt.attendees && evt.attendees.length > 0 && (
                    <div className="flex items-center gap-2">
                      <Users className="w-3.5 h-3.5 text-slate-500" />
                      <span>{evt.attendees.length} asistentes invitados</span>
                    </div>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Create Event Modal */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-md overflow-hidden shadow-2xl">
            <div className="p-4 border-b border-slate-800 flex items-center justify-between">
              <h3 className="font-bold text-slate-100 text-sm">Programar Evento de Equipo</h3>
              <button onClick={() => setIsCreateModalOpen(false)} className="text-slate-400 hover:text-white">
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleCreateEvent} className="p-4 space-y-3">
              <div>
                <label className="block text-slate-400 mb-1 font-medium">Título</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={e => setNewTitle(e.target.value)}
                  placeholder="Ej: Sprint Planning Sprint 25"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:outline-none focus:border-amber-500"
                />
              </div>

              <div>
                <label className="block text-slate-400 mb-1">Descripción</label>
                <textarea
                  rows={2}
                  value={newDescription}
                  onChange={e => setNewDescription(e.target.value)}
                  placeholder="Objetivos de la reunión..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:outline-none focus:border-amber-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-slate-400 mb-1">Inicio</label>
                  <input
                    type="datetime-local"
                    required
                    value={newStart}
                    onChange={e => setNewStart(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-slate-100 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-slate-400 mb-1">Fin</label>
                  <input
                    type="datetime-local"
                    value={newEnd}
                    onChange={e => setNewEnd(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-slate-100 focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-slate-400 mb-1">Ubicación / Sala</label>
                <input
                  type="text"
                  value={newLocation}
                  onChange={e => setNewLocation(e.target.value)}
                  placeholder="Ej: Sala Virtual Nexora o Oficina Principal"
                  className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:outline-none"
                />
              </div>

              <div className="pt-2 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 text-slate-300 hover:bg-slate-700"
                >
                  Cancelar
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 rounded-lg bg-amber-600 text-white font-semibold hover:bg-amber-500 shadow-md shadow-amber-600/30"
                >
                  Programar
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

// frontend/src/app/features/calendar/calendar-view.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CalendarApiService } from '../../core/http/calendar-api.service';
import { ToastService } from '../../core/services/toast.service';
import { CalendarEvent } from '../../core/models/task.model';
import { LoadingStateComponent } from '../../shared/components/loading-state/loading-state.component';

@Component({
  selector: 'app-calendar-view',
  standalone: true,
  imports: [CommonModule, FormsModule, LoadingStateComponent],
  template: `
    <div class="flex-1 flex flex-col h-full w-full bg-slate-950 overflow-hidden">
      <!-- HEADER -->
      <header class="h-14 border-b border-slate-800 bg-slate-900/60 backdrop-blur-xs flex items-center justify-between px-6 shrink-0">
        <div class="flex items-center gap-3">
          <div class="w-8 h-8 rounded-lg bg-violet-600/20 text-violet-400 flex items-center justify-center">
            <span class="material-icons-round text-lg">calendar_month</span>
          </div>
          <div>
            <h2 class="text-sm font-bold text-slate-100">Calendario & Eventos</h2>
            <p class="text-[11px] text-slate-400">Planificación de sincronizaciones, demos y entregas de sprint</p>
          </div>
        </div>

        <button
          type="button"
          (click)="openModal()"
          class="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs rounded-lg transition-colors flex items-center gap-1.5 shadow-sm cursor-pointer"
        >
          <span class="material-icons-round text-sm">event</span>
          <span>Programar Evento</span>
        </button>
      </header>

      <!-- CONTENT GRID -->
      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <app-loading-state *ngIf="isLoading()" message="Sincronizando eventos del calendario..."></app-loading-state>

        <div *ngIf="!isLoading()" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div
            *ngFor="let ev of events()"
            class="bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-xl p-4 space-y-3 transition-colors shadow-xs"
          >
            <div class="flex items-start justify-between gap-2">
              <span class="text-xs font-bold text-slate-100">{{ ev.title }}</span>
              <span class="material-icons-round text-slate-500 text-sm">schedule</span>
            </div>

            <p *ngIf="ev.description" class="text-xs text-slate-400 leading-relaxed">{{ ev.description }}</p>

            <div class="space-y-1 text-[11px] text-slate-400 pt-2 border-t border-slate-800/80 font-mono">
              <div class="flex items-center gap-1.5">
                <span class="material-icons-round text-xs text-indigo-400">access_time</span>
                <span>{{ ev.startTime | date:'shortTime' }} - {{ ev.endTime | date:'shortTime' }}</span>
              </div>
              <div class="flex items-center gap-1.5">
                <span class="material-icons-round text-xs text-indigo-400">calendar_today</span>
                <span>{{ ev.startTime | date:'fullDate' }}</span>
              </div>
            </div>

            <div class="flex justify-end pt-1">
              <button
                (click)="deleteEvent(ev.id)"
                class="text-slate-500 hover:text-red-400 text-xs flex items-center gap-1 cursor-pointer transition-colors"
              >
                <span class="material-icons-round text-xs">delete</span>
                <span>Eliminar</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- SCHEDULE EVENT MODAL -->
      <div *ngIf="isModalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs">
        <div class="bg-slate-900 border border-slate-800 rounded-xl max-w-md w-full p-5 space-y-3 shadow-2xl">
          <div class="flex items-center justify-between pb-2 border-b border-slate-800">
            <h3 class="text-xs font-bold text-slate-100 uppercase tracking-wide">Agendar Evento</h3>
            <button (click)="isModalOpen = false" class="text-slate-400 hover:text-slate-200 cursor-pointer">
              <span class="material-icons-round text-base">close</span>
            </button>
          </div>

          <div class="space-y-3">
            <div>
              <label class="block text-xs text-slate-300 mb-1">Título</label>
              <input
                type="text"
                [(ngModel)]="newTitle"
                placeholder="Ej. Daily Scrum o Demostración Sprint"
                class="w-full h-9 bg-slate-950 border border-slate-800 rounded-lg px-3 text-xs text-slate-100 focus:outline-hidden focus:border-indigo-500"
              />
            </div>

            <div>
              <label class="block text-xs text-slate-300 mb-1">Descripción</label>
              <textarea
                [(ngModel)]="newDescription"
                rows="2"
                placeholder="Temas a tratar en la sesión..."
                class="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-slate-100 focus:outline-hidden focus:border-indigo-500"
              ></textarea>
            </div>

            <div class="grid grid-cols-2 gap-3">
              <div>
                <label class="block text-xs text-slate-300 mb-1">Fecha y Hora Inicio</label>
                <input
                  type="datetime-local"
                  [(ngModel)]="newStartTime"
                  class="w-full h-9 bg-slate-950 border border-slate-800 rounded-lg px-2 text-xs text-slate-100 focus:outline-hidden"
                />
              </div>

              <div>
                <label class="block text-xs text-slate-300 mb-1">Fecha y Hora Fin</label>
                <input
                  type="datetime-local"
                  [(ngModel)]="newEndTime"
                  class="w-full h-9 bg-slate-950 border border-slate-800 rounded-lg px-2 text-xs text-slate-100 focus:outline-hidden"
                />
              </div>
            </div>
          </div>

          <div class="flex justify-end gap-2 pt-3 border-t border-slate-800">
            <button
              type="button"
              (click)="isModalOpen = false"
              class="px-3 py-1.5 text-xs text-slate-400 hover:text-white cursor-pointer"
            >
              Cancelar
            </button>
            <button
              type="button"
              (click)="saveEvent()"
              [disabled]="!newTitle.trim() || !newStartTime"
              class="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-medium text-xs rounded-lg cursor-pointer"
            >
              Agendar
            </button>
          </div>
        </div>
      </div>
    </div>
  `
})
export class CalendarViewComponent implements OnInit {
  public events = signal<CalendarEvent[]>([]);
  public isLoading = signal<boolean>(true);
  public isModalOpen = false;

  public newTitle = '';
  public newDescription = '';
  public newStartTime = '';
  public newEndTime = '';

  constructor(
    private calendarApi: CalendarApiService,
    private toastService: ToastService
  ) {}

  ngOnInit(): void {
    this.loadEvents();
  }

  loadEvents(): void {
    this.isLoading.set(true);
    this.calendarApi.getEvents().subscribe({
      next: data => {
        this.events.set(data);
        this.isLoading.set(false);
      },
      error: () => this.isLoading.set(false)
    });
  }

  openModal(): void {
    this.newTitle = '';
    this.newDescription = '';
    const now = new Date();
    this.newStartTime = now.toISOString().slice(0, 16);
    now.setHours(now.getHours() + 1);
    this.newEndTime = now.toISOString().slice(0, 16);
    this.isModalOpen = true;
  }

  saveEvent(): void {
    if (!this.newTitle.trim() || !this.newStartTime) return;

    this.calendarApi.scheduleEvent({
      title: this.newTitle.trim(),
      description: this.newDescription.trim(),
      startTime: new Date(this.newStartTime).toISOString(),
      endTime: this.newEndTime ? new Date(this.newEndTime).toISOString() : new Date(this.newStartTime).toISOString()
    }).subscribe({
      next: created => {
        this.events.update(list => [created, ...list]);
        this.toastService.success('Evento agendado exitosamente.');
        this.isModalOpen = false;
      },
      error: () => this.toastService.error('Error al agendar evento.')
    });
  }

  deleteEvent(id: string): void {
    this.calendarApi.deleteEvent(id).subscribe({
      next: () => {
        this.events.update(list => list.filter(e => e.id !== id));
        this.toastService.success('Evento eliminado.');
      },
      error: () => this.toastService.error('Error al eliminar evento.')
    });
  }
}
